// src/routes/_components/ColorTable.svelte
<script lang="ts">
  import { ToggleGroup } from 'bits-ui';
  import { t, type Language } from '$lib/i18n';
  import type { ColorData, ColorFormat, SceneConfig } from '$lib/types';
  import ColorRow from './ColorRow.svelte';

  interface Props {
    sourceColors: ColorData[];
    adjustedColors: ColorData[];
    scene: SceneConfig;
    format: ColorFormat;
    language: Language;
    primaryColorId: string | null;
    onPrimaryChange: (id: string) => void;
    onCopyText: (text: string) => void;
  }

  let {
    sourceColors,
    adjustedColors,
    scene,
    format = $bindable(),
    language,
    primaryColorId,
    onPrimaryChange,
    onCopyText,
  }: Props = $props();
</script>

<main class="flex min-h-0 flex-1 flex-col overflow-hidden">
  {#if sourceColors.length === 0}
    <div class="flex flex-1 items-center justify-center text-neutral-600">
      <div class="text-center">
        <p class="text-sm">{t('warn_no_colors', language)}</p>
        <p class="mt-1 text-xs text-neutral-700">{t('warn_paste_hint', language)}</p>
      </div>
    </div>
  {:else}
    <div
      class="grid grid-cols-[30px_minmax(180px,1fr)_40px_minmax(220px,1.2fr)_120px_130px] items-center gap-4 border-b border-neutral-800 bg-neutral-950 px-4 py-2 text-xs font-medium uppercase tracking-wider text-neutral-500"
    >
      <div></div>
      <div>{t('col_source', language)}</div>
      <div></div>
      <div class="flex items-center gap-2">
        <span>{t('col_adjusted', language)}</span>
        <ToggleGroup.Root bind:value={format} type="single" class="flex rounded border border-neutral-800 bg-neutral-900 p-0.5 font-mono">
          <ToggleGroup.Item
            value="oklch"
            class="rounded-sm px-1.5 py-0.5 text-[10px] text-neutral-600 data-[state=on]:bg-neutral-700 data-[state=on]:text-white"
          >
            OKLCH
          </ToggleGroup.Item>
          <ToggleGroup.Item
            value="hex"
            class="rounded-sm px-1.5 py-0.5 text-[10px] text-neutral-600 data-[state=on]:bg-neutral-700 data-[state=on]:text-white"
          >
            HEX
          </ToggleGroup.Item>
        </ToggleGroup.Root>
      </div>
      <div>{t('col_apca', language)}</div>
      <div>{t('col_rating', language)}</div>
    </div>

    <div class="min-h-0 flex-1 overflow-auto">
      {#each sourceColors as source, index (source.id)}
        {@const adjusted = adjustedColors[index]}
        {#if adjusted}
          <ColorRow
            {source}
            {adjusted}
            {scene}
            {format}
            {language}
            isPrimary={source.id === primaryColorId}
            {onPrimaryChange}
            {onCopyText}
          />
        {/if}
      {/each}
    </div>
  {/if}
</main>

// src/components/data/ColorTable.tsx

import { ColorRow } from './ColorRow';
import type { ColorData, SceneConfig, ColorFormat } from '../../lib/types';
import { t, type Language } from '../../lib/i18n';
import { clsx } from 'clsx';

interface ColorTableProps {
    sourceColors: ColorData[];
    adjustedColors: ColorData[];
    scene: SceneConfig;
    lang: Language;
    primaryColorId: string | null;
    onPrimaryChange: (id: string) => void;
    format: ColorFormat;
    onFormatChange: (format: ColorFormat) => void;
}

export function ColorTable({ sourceColors, adjustedColors, scene, lang, primaryColorId, onPrimaryChange, format, onFormatChange }: ColorTableProps) {
    if (sourceColors.length === 0) {
        return (
            <div className="flex-1 flex items-center justify-center text-neutral-600">
                <div className="text-center">
                    <p className="text-sm">{t('warn_no_colors', lang)}</p>
                    <p className="text-xs mt-1 text-neutral-700">{t('warn_paste_hint', lang)}</p>
                </div>
            </div>
        );
    }

    return (
        <div className="flex-1 overflow-hidden flex flex-col min-h-0">
            {/* Header */}
            <div className="grid grid-cols-[30px_1fr_40px_1fr_120px_120px] gap-4 px-4 py-2 border-b border-neutral-800 bg-neutral-950 text-xs font-medium text-neutral-500 uppercase tracking-wider sticky top-0 z-10">
                <div></div>
                <div>{t('col_source', lang)}</div>
                <div></div>
                <div className="flex items-center gap-2">
                    <span>{t('col_adjusted', lang)}</span>
                    <div className="flex bg-neutral-900 rounded p-[2px] border border-neutral-800">
                        <button 
                            onClick={() => onFormatChange('oklch')}
                            className={clsx(
                                "text-[10px] px-1.5 py-0.5 rounded-[2px] transition-all font-mono leading-none",
                                format === 'oklch' ? "bg-neutral-700 text-white shadow-sm" : "text-neutral-600 hover:text-neutral-400"
                            )}
                        >
                            OKLCH
                        </button>
                        <button 
                            onClick={() => onFormatChange('hex')}
                            className={clsx(
                                "text-[10px] px-1.5 py-0.5 rounded-[2px] transition-all font-mono leading-none",
                                format === 'hex' ? "bg-neutral-700 text-white shadow-sm" : "text-neutral-600 hover:text-neutral-400"
                            )}
                        >
                            HEX
                        </button>
                    </div>
                </div>
                <div>{t('col_apca', lang)}</div>
                <div>{t('col_rating', lang)}</div>
            </div>
            
            {/* Scrollable List */}
            <div className="flex-1 overflow-y-auto min-h-0">
                {sourceColors.map((source, index) => {
                    const adjusted = adjustedColors[index];
                    if (!adjusted) return null;
                    
                    return (
                        <ColorRow
                            key={`${source.id}-${index}`}
                            source={source}
                            adjusted={adjusted}
                            scene={scene}
                            lang={lang}
                            isPrimary={source.id === primaryColorId}
                            onSetPrimary={() => onPrimaryChange(source.id)}
                            format={format}
                        />
                    );
                })}
            </div>
        </div>
    );
}
