// src/components/data/ColorRow.tsx
import React, { useState } from 'react';
import { ArrowRight, Copy, Check } from 'lucide-react';
import { clsx } from 'clsx';
import { getApcaContrast, getApcaRating } from '../../lib/color-utils';
import type { ColorData, SceneConfig } from '../../lib/types';
import { t, type Language } from '../../lib/i18n';

interface ColorRowProps {
    source: ColorData;
    adjusted: ColorData;
    scene: SceneConfig;
    lang: Language;
}

export function ColorRow({ source, adjusted, scene, lang }: ColorRowProps) {
    const [copied, setCopied] = useState<string | null>(null);

    const handleCopy = (hex: string, type: 'source' | 'adjusted') => {
        navigator.clipboard.writeText(hex);
        setCopied(type);
        setTimeout(() => setCopied(null), 1500);
    };

    // APCA Metrics
    const refHex = scene.apcaTarget?.reference === 'white' ? '#ffffff' : '#000000';
    const apcaScore = getApcaContrast(adjusted.hex, refHex);
    const apcaRating = getApcaRating(apcaScore);
    const apcaMag = Math.abs(apcaScore);
    
    // Status Color
    let statusColor = 'text-emerald-500';
    if (scene.apcaTarget) {
        if (apcaMag < scene.apcaTarget.min) statusColor = 'text-red-500';
        else if (apcaMag < scene.apcaTarget.optimal) statusColor = 'text-yellow-500';
    }

    return (
        <div className="grid grid-cols-[1fr_40px_1fr_120px_120px] gap-4 items-center py-2 px-4 border-b border-neutral-800 hover:bg-neutral-900/50 group transition-colors text-sm">
            {/* Source */}
            <div className="flex items-center gap-3">
                <div 
                    className="w-8 h-8 rounded-sm border border-white/10 shadow-sm"
                    style={{ backgroundColor: source.hex }}
                />
                <div className="font-mono text-neutral-400 group-hover:text-neutral-300 cursor-pointer" onClick={() => handleCopy(source.hex, 'source')}>
                    {source.hex}
                </div>
                {copied === 'source' && <Check size={12} className="text-emerald-500" />}
            </div>

            {/* Arrow */}
            <div className="flex justify-center text-neutral-600">
                <ArrowRight size={14} />
            </div>

            {/* Adjusted */}
            <div className="flex items-center gap-3">
                <div 
                    className="w-8 h-8 rounded-sm border border-white/10 shadow-sm relative group/preview"
                    style={{ backgroundColor: adjusted.hex }}
                >
                    <div className="absolute inset-0 flex items-center justify-center opacity-0 group-hover/preview:opacity-100 bg-black/20 transition-opacity cursor-pointer" onClick={() => handleCopy(adjusted.hex, 'adjusted')}>
                        <Copy size={12} className="text-white" />
                    </div>
                </div>
                <div className="font-mono text-neutral-200 font-medium cursor-pointer" onClick={() => handleCopy(adjusted.hex, 'adjusted')}>
                    {adjusted.hex}
                </div>
                {copied === 'adjusted' && <Check size={12} className="text-emerald-500" />}
            </div>

            {/* Metrics */}
            <div className="flex flex-col justify-center">
                <div className="font-mono text-neutral-300">
                    Lc {apcaScore.toFixed(1)}
                </div>
                {scene.apcaTarget && (
                    <div className="text-[10px] text-neutral-500 mt-0.5">
                        {t('label_target', lang)}: {scene.apcaTarget.min}-{scene.apcaTarget.max}
                    </div>
                )}
            </div>

            {/* Status */}
            <div className={clsx("font-medium text-xs flex items-center gap-2", statusColor)}>
                <div className={clsx("w-1.5 h-1.5 rounded-full bg-current")} />
                {apcaRating}
            </div>
        </div>
    );
}

// src/routes/_components/ColorRow.svelte
<script lang="ts">
  import { calcAPCA } from 'apca-w3';
  import { Button } from 'bits-ui';
  import { ArrowRight, Check, Copy } from 'lucide-svelte';
  import { formatColor, getApcaRating } from '$lib/color';
  import { t, type Language } from '$lib/i18n';
  import type { ColorData, ColorFormat, SceneConfig } from '$lib/types';

  interface Props {
    source: ColorData;
    adjusted: ColorData;
    scene: SceneConfig;
    format: ColorFormat;
    language: Language;
    isPrimary: boolean;
    onPrimaryChange: (id: string) => void;
    onCopyText: (text: string) => void;
  }

  let {
    source,
    adjusted,
    scene,
    format,
    language,
    isPrimary,
    onPrimaryChange,
    onCopyText,
  }: Props = $props();
  let copied = $state<'source' | 'adjusted' | null>(null);

  function copy(kind: 'source' | 'adjusted', text: string) {
    onCopyText(text);
    copied = kind;
    setTimeout(() => (copied = null), 1500);
  }

  let sourceText = $derived(formatColor(source, format));
  let adjustedText = $derived(formatColor(adjusted, format));
  let referenceHex = $derived(scene.apcaTarget?.reference === 'black' ? '#000000' : '#ffffff');
  let score = $derived(calcAPCA(adjusted.hex, referenceHex) as number);
  let statusClass = $derived.by(() => {
    const target = scene.apcaTarget;
    const mag = Math.abs(score);

    if (!target) return 'text-emerald-500';
    if (mag < target.min) return 'text-red-500';
    if (mag < target.optimal) return 'text-yellow-500';
    return 'text-emerald-500';
  });
</script>

<div
  class={`grid grid-cols-[30px_minmax(180px,1fr)_40px_minmax(220px,1.2fr)_120px_130px] items-center gap-4 border-b border-neutral-800 px-4 py-2 text-sm transition-colors hover:bg-neutral-900/50 ${isPrimary ? 'bg-neutral-900/30' : ''}`}
>
  <Button.Root
    class="flex h-8 items-center justify-center"
    aria-label={t('set_primary', language)}
    onclick={() => onPrimaryChange(source.id)}
  >
    <span
      class={`h-1.5 w-1.5 rounded-full ${isPrimary ? 'bg-emerald-500 shadow-[0_0_8px_rgba(16,185,129,0.5)]' : 'bg-neutral-700'}`}
    ></span>
  </Button.Root>

  <Button.Root class="flex items-center gap-3 text-left" onclick={() => copy('source', sourceText)}>
    <span class="h-8 w-8 rounded-sm border border-white/10 shadow-sm" style:background-color={source.hex}></span>
    <span class="font-mono text-neutral-400">{sourceText}</span>
    {#if copied === 'source'}
      <Check size={12} class="text-emerald-500" />
    {/if}
  </Button.Root>

  <div class="flex justify-center text-neutral-600">
    <ArrowRight size={14} />
  </div>

  <Button.Root class="flex items-center gap-3 text-left" onclick={() => copy('adjusted', adjustedText)}>
    <span class="group/preview relative h-8 w-8 rounded-sm border border-white/10 shadow-sm" style:background-color={adjusted.hex}>
      <span class="absolute inset-0 flex items-center justify-center bg-black/20 opacity-0 transition-opacity group-hover/preview:opacity-100">
        <Copy size={12} class="text-white" />
      </span>
    </span>
    <span class="font-mono font-medium text-neutral-200">{adjustedText}</span>
    {#if format === 'oklch'}
      <span class="rounded border border-neutral-800 bg-neutral-900 px-1.5 py-0.5 font-mono text-[10px] text-neutral-500">
        {adjusted.hex}
      </span>
    {/if}
    {#if copied === 'adjusted'}
      <Check size={12} class="text-emerald-500" />
    {/if}
  </Button.Root>

  <div class="font-mono text-neutral-300">
    Lc {score.toFixed(1)}
    {#if scene.apcaTarget}
      <div class="mt-0.5 text-[10px] text-neutral-500">
        {t('label_target', language)}: {scene.apcaTarget.min}-{scene.apcaTarget.max}
      </div>
    {/if}
  </div>

  <div class={`flex items-center gap-2 text-xs font-medium ${statusClass}`}>
    <span class="h-1.5 w-1.5 rounded-full bg-current"></span>
    {getApcaRating(score)}
  </div>
</div>
