// src/components/layout/StatusBar.tsx

import { useState } from 'react';
import { Download, Copy, Globe, Check } from 'lucide-react';
import { t, type Language } from '../../lib/i18n';
import { clsx } from 'clsx';

interface StatusBarProps {
    parsedCount: number;
    sceneName: string;
    onExportJson: () => void;
    onCopyCss: () => void;
    lang: Language;
    onLanguageChange: (lang: Language) => void;
}

export function StatusBar({ parsedCount, sceneName, onExportJson, onCopyCss, lang, onLanguageChange }: StatusBarProps) {
    const [copied, setCopied] = useState(false);

    const handleCopy = () => {
        onCopyCss();
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    return (
        <div className="flex-none h-10 min-h-[40px] bg-neutral-950 border-t border-neutral-800 flex items-center justify-between px-4 select-none">
            <div className="flex items-center gap-4 text-xs text-neutral-500 font-mono">
                <span>{parsedCount} {t('status_colors_parsed', lang)}</span>
                <span className="w-px h-3 bg-neutral-800" />
                <span>{t('scene_title', lang)}: {sceneName}</span>
            </div>
            
            <div className="flex items-center gap-2">
                <button
                    onClick={onExportJson}
                    className="flex items-center gap-1.5 px-3 py-1 hover:bg-neutral-900 text-xs text-neutral-400 hover:text-neutral-200 transition-colors rounded-sm"
                    title={t('status_export_json', lang)}
                >
                    <Download size={12} />
                    <span>JSON</span>
                </button>
                <button
                    onClick={handleCopy}
                    className="flex items-center gap-1.5 px-3 py-1 hover:bg-neutral-900 text-xs text-neutral-400 hover:text-neutral-200 transition-colors rounded-sm"
                    title={t('status_copy_css', lang)}
                >
                    {copied ? <Check size={12} className="text-emerald-500" /> : <Copy size={12} />}
                    <span className={clsx(copied && "text-emerald-500")}>
                        {copied ? t('status_copied', lang) : 'CSS'}
                    </span>
                </button>

                <div className="w-px h-3 bg-neutral-800 mx-2" />

                <button
                    onClick={() => onLanguageChange(lang === 'en' ? 'zh' : 'en')}
                    className="flex items-center gap-1.5 px-3 py-1 hover:bg-neutral-900 text-xs text-neutral-400 hover:text-neutral-200 transition-colors rounded-sm"
                    title="Switch Language"
                >
                    <Globe size={12} />
                    <span className={clsx(lang === 'en' ? "font-sans" : "font-mono")}>
                        {lang === 'en' ? '中文' : 'EN'}
                    </span>
                </button>
            </div>
        </div>
    );
}

// src/routes/_components/StatusBar.svelte
<script lang="ts">
  import { Button } from 'bits-ui';
  import { Check, Copy, Download, Globe } from 'lucide-svelte';
  import { t, type Language } from '$lib/i18n';

  interface Props {
    parsedCount: number;
    sceneName: string;
    language: Language;
    copiedCss: boolean;
    onExportJson: () => void;
    onCopyCss: () => void;
  }

  let { parsedCount, sceneName, language = $bindable(), copiedCss, onExportJson, onCopyCss }: Props = $props();

  let languageToggleLabel = $derived(language === 'en' ? '中文' : 'EN');

  function toggleLanguage() {
    language = language === 'en' ? 'zh' : 'en';
  }
</script>

<footer class="flex h-10 flex-none items-center justify-between border-t border-neutral-800 bg-neutral-950 px-4 text-xs text-neutral-500">
  <div class="flex items-center gap-4 font-mono">
    <span>{parsedCount} {t('status_colors_parsed', language)}</span>
    <span class="h-3 w-px bg-neutral-800"></span>
    <span>{t('scene_title', language)}: {sceneName}</span>
  </div>

  <div class="flex items-center gap-2">
    <Button.Root
      class="flex items-center gap-1.5 rounded-sm px-3 py-1 text-neutral-400 transition-colors hover:bg-neutral-900 hover:text-neutral-200"
      onclick={onExportJson}
    >
      <Download size={12} />
      <span>JSON</span>
    </Button.Root>
    <Button.Root
      class="flex items-center gap-1.5 rounded-sm px-3 py-1 text-neutral-400 transition-colors hover:bg-neutral-900 hover:text-neutral-200"
      onclick={onCopyCss}
    >
      {#if copiedCss}
        <Check size={12} class="text-emerald-500" />
      {:else}
        <Copy size={12} />
      {/if}
      <span class={copiedCss ? 'text-emerald-500' : ''}>{copiedCss ? t('status_copied', language) : 'CSS'}</span>
    </Button.Root>
    <span class="mx-2 h-3 w-px bg-neutral-800"></span>
    <Button.Root
      class="flex items-center gap-1.5 rounded-sm px-3 py-1 text-neutral-400 transition-colors hover:bg-neutral-900 hover:text-neutral-200"
      onclick={toggleLanguage}
    >
      <Globe size={12} />
      <span>{languageToggleLabel}</span>
    </Button.Root>
  </div>
</footer>
